AllCops:
  Exclude:
    - Guardfile
    - vendor/**/*
    - spec/**/*
    - example.rb
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 100
Style/SpecialGlobalVars:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
